#!/bin/sh

# Super+C to spawn firefox
riverctl map normal Super C spawn "MOZ_ENABLE_WAYLAND=1 firefox"

# Super+S to spawn bemenu
riverctl map normal Super S spawn "fuzzel -I -b ffffffff -w 100 -B 0"

# Super+V to spawn terminal
riverctl map normal Super V spawn alacritty

# Super+F to spawn emacs
riverctl map normal Super F spawn emacs

# Super+T to focus next
riverctl map normal Super T swap next

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+Q to exit river
riverctl map normal Super+Shift Q exit

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag
    riverctl map normal Super $i set-focused-tags $tags
done

# Set background and border color
riverctl background-color 0xf7f3ee

# Set keyboard repeat rate
riverctl set-repeat 50 200

# Set no border pixels
riverctl border-width 0

# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
rivercarro -no-smart-gaps -inner-gaps 0 -outer-gaps 0 -main-ratio 1.0
