#!/usr/bin/env bash
set -Eeuo pipefail
read -p "github username: " USER
PAGES=$(curl -s -I https://api.github.com/users/$USER/repos | grep link | sed 's/^.*page=//;s/>.*//')
for PAGE in $(seq 1 $PAGES); do
    REPOS=$(curl -s https://api.github.com/users/$USER/repos?page=$PAGE | jq -r ".[].full_name")
    for REPO in $REPOS ; do
        git clone "https://github.com/$REPO"
    done    
done
