#!/usr/bin/env bash
set -Eeuxo pipefail
MUPDF="$HOME/.scripts/mupdf"
declare -A booklist; declare -a index
while read -r i; do
    location="$i"
    title="${i##*/}"
    booklist[$title]="$location"; index+=( "$title" )
done < <(cat "$HOME/.cache/pdfcache" | cut -f 1)
select="$(printf '%s\n' "${index[@]}" | dmenu -p "pdf" -l 5)"
[ -z "$select" ] && exit 1
exec $MUPDF "${booklist[$select]}" &
exit 0
