#!/usr/bin/env bash
set -Eeuxo pipefail
FOLDER="$HOME/downloads"
BACKUP="$HOME/source/backup"
FILE=$(find $FOLDER -type f | sort | $DMENU -l 5)
FILENAME=$(basename -- "$FILE")
EXTENSION="${FILENAME##*.}"
if [[ -n $EXTENSION ]]; then
    cd "$BACKUP" && mkdir -p "$EXTENSION" && cd "$EXTENSION"
    NAME=$(dmenu -l 0 -p <<< "$FILENAME")
    mv "$FILE" "./$NAME"
fi
