#!/usr/bin/env bash
set -Eeuo pipefail
FOLDER="$HOME/.cache/jpg-pdf"
if [ -z "$1" ]; then
    printf "$FILE <zip>\n"
else
    mkdir -p "$FOLDER" && cp "$1" "$FOLDER/images.zip" && cd "$FOLDER"
    unzip images.zip
    convert "*.{jpg}" -quality 80 "$HOME/bilder.pdf"
    ls -alh "$HOME/bilder.pdf"
    rm -r "$FOLDER"
fi
